/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 12-08-2021 11:56:05
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package org.inspirecenter.amazechallenge.model;

import com.nkasenides.athlos.proto.Transmittable;
import org.inspirecenter.amazechallenge.proto.*;
import com.nkasenides.athlos.model.*;
import org.inspirecenter.amazechallenge.proto.AMCTerrainCellProto;

public class AMCTerrainCell implements Transmittable<AMCTerrainCellProto.Builder>, ITerrainCell {
    private MatrixPosition position;    
    private boolean rightWall;    
    private boolean downWall;    
    private boolean upWall;    
    private boolean leftWall;    

    public MatrixPosition getPosition() {    
        return position;        
    }    
    
    public boolean isRightWall() {    
        return rightWall;        
    }    
    
    public boolean isDownWall() {    
        return downWall;        
    }    
    
    public boolean isUpWall() {    
        return upWall;        
    }    
    
    public boolean isLeftWall() {    
        return leftWall;        
    }    
    

    public void setPosition(MatrixPosition position) {    
        this.position = position;        
    }    
    
    public void setRightWall(boolean rightWall) {    
        this.rightWall = rightWall;        
    }    
    
    public void setDownWall(boolean downWall) {    
        this.downWall = downWall;        
    }    
    
    public void setUpWall(boolean upWall) {    
        this.upWall = upWall;        
    }    
    
    public void setLeftWall(boolean leftWall) {    
        this.leftWall = leftWall;        
    }    
    

    @Override    
    public AMCTerrainCellProto.Builder toProto() {
        AMCTerrainCellProto.Builder protoBuilder = AMCTerrainCellProto.newBuilder();
        protoBuilder.setPosition(position.toProto().build());        
        protoBuilder.setRightWall(rightWall);        
        protoBuilder.setDownWall(downWall);        
        protoBuilder.setUpWall(upWall);        
        protoBuilder.setLeftWall(leftWall);        
        return protoBuilder;        
    }    
    

}
