/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 25-09-2021 13:52:52
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package org.inspirecenter.amazechallenge.model;

import java.util.ArrayList;
import java.util.List;
import com.nkasenides.athlos.proto.Transmittable;
import com.nkasenides.athlos.proto.GenericTransmittable;
import com.raylabz.firestorm.annotation.FirestormObject;
import org.inspirecenter.amazechallenge.proto.*;
import com.nkasenides.athlos.model.*;

@FirestormObject
public class QuestionnaireEntry implements Transmittable<QuestionnaireEntryProto.Builder> {
    private String challengeID;    
    private ArrayList<QuestionEntry> questionEntry = new ArrayList<>();    
    private String id;    
    private String participantName;    
    private String participantEmail;    

    public String getChallengeID() {    
        return challengeID;        
    }    
    
    public List<QuestionEntry> getQuestionEntry() {
        return questionEntry;        
    }    
    
    public String getId() {    
        return id;        
    }    
    
    public String getParticipantName() {    
        return participantName;        
    }    
    
    public String getParticipantEmail() {    
        return participantEmail;        
    }    
    

    public void setChallengeID(String challengeID) {    
        this.challengeID = challengeID;        
    }    
    
    public void setQuestionEntry(ArrayList<QuestionEntry> questionEntry) {
        this.questionEntry = questionEntry;        
    }    
    
    public void setId(String id) {    
        this.id = id;        
    }    
    
    public void setParticipantName(String participantName) {    
        this.participantName = participantName;        
    }    
    
    public void setParticipantEmail(String participantEmail) {    
        this.participantEmail = participantEmail;        
    }    
    

    @Override    
    public QuestionnaireEntryProto.Builder toProto() {
        QuestionnaireEntryProto.Builder protoBuilder = QuestionnaireEntryProto.newBuilder();
        protoBuilder.setChallengeID(challengeID);        
        ArrayList<QuestionEntryProto> questionEntryList = new ArrayList<>();
        for (int i = 0; i < questionEntry.size(); i++) {        
            questionEntryList.add(questionEntry.get(i).toProto().build());            
        }        
        protoBuilder.addAllQuestionEntry(questionEntryList);        
        protoBuilder.setId(id);        
        protoBuilder.setParticipantName(participantName);        
        protoBuilder.setParticipantEmail(participantEmail);        
        return protoBuilder;        
    }    
    

}
