// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/AMCProto.proto

package com.nkasenides.amc.proto;

public interface AMCGameSessionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.amc.proto.AMCGameSessionProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ipAddress = 1;</code>
   * @return The ipAddress.
   */
  String getIpAddress();
  /**
   * <code>string ipAddress = 1;</code>
   * @return The bytes for ipAddress.
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <code>uint64 expiresOn = 2;</code>
   * @return The expiresOn.
   */
  long getExpiresOn();

  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>uint64 createdOn = 4;</code>
   * @return The createdOn.
   */
  long getCreatedOn();

  /**
   * <code>string playerID = 5;</code>
   * @return The playerID.
   */
  String getPlayerID();
  /**
   * <code>string playerID = 5;</code>
   * @return The bytes for playerID.
   */
  com.google.protobuf.ByteString
      getPlayerIDBytes();
}
