// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/AMCProto.proto

package com.nkasenides.amc.proto;

/**
 * Protobuf type {@code com.nkasenides.amc.proto.AMCStateUpdateProto}
 */
public final class AMCStateUpdateProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.nkasenides.amc.proto.AMCStateUpdateProto)
    AMCStateUpdateProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AMCStateUpdateProto.newBuilder() to construct.
  private AMCStateUpdateProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AMCStateUpdateProto() {
    worldSessionID_ = "";
    removedEntities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    removedTerrain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new AMCStateUpdateProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AMCStateUpdateProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            AMCPartialStateProto.Builder subBuilder = null;
            if (partialState_ != null) {
              subBuilder = partialState_.toBuilder();
            }
            partialState_ = input.readMessage(AMCPartialStateProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(partialState_);
              partialState_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            worldSessionID_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              removedEntities_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            removedEntities_.add(s);
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              removedTerrain_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            removedTerrain_.add(s);
            break;
          }
          case 40: {

            timestamp_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        removedEntities_ = removedEntities_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        removedTerrain_ = removedTerrain_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return AMCProto.internal_static_com_nkasenides_amc_proto_AMCStateUpdateProto_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return AMCProto.internal_static_com_nkasenides_amc_proto_AMCStateUpdateProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AMCStateUpdateProto.class, Builder.class);
  }

  public static final int PARTIALSTATE_FIELD_NUMBER = 1;
  private AMCPartialStateProto partialState_;
  /**
   * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
   * @return Whether the partialState field is set.
   */
  @Override
  public boolean hasPartialState() {
    return partialState_ != null;
  }
  /**
   * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
   * @return The partialState.
   */
  @Override
  public AMCPartialStateProto getPartialState() {
    return partialState_ == null ? AMCPartialStateProto.getDefaultInstance() : partialState_;
  }
  /**
   * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
   */
  @Override
  public AMCPartialStateProtoOrBuilder getPartialStateOrBuilder() {
    return getPartialState();
  }

  public static final int WORLDSESSIONID_FIELD_NUMBER = 2;
  private volatile Object worldSessionID_;
  /**
   * <code>string worldSessionID = 2;</code>
   * @return The worldSessionID.
   */
  @Override
  public String getWorldSessionID() {
    Object ref = worldSessionID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      worldSessionID_ = s;
      return s;
    }
  }
  /**
   * <code>string worldSessionID = 2;</code>
   * @return The bytes for worldSessionID.
   */
  @Override
  public com.google.protobuf.ByteString
      getWorldSessionIDBytes() {
    Object ref = worldSessionID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      worldSessionID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMOVEDENTITIES_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList removedEntities_;
  /**
   * <code>repeated string removedEntities = 3;</code>
   * @return A list containing the removedEntities.
   */
  public com.google.protobuf.ProtocolStringList
      getRemovedEntitiesList() {
    return removedEntities_;
  }
  /**
   * <code>repeated string removedEntities = 3;</code>
   * @return The count of removedEntities.
   */
  public int getRemovedEntitiesCount() {
    return removedEntities_.size();
  }
  /**
   * <code>repeated string removedEntities = 3;</code>
   * @param index The index of the element to return.
   * @return The removedEntities at the given index.
   */
  public String getRemovedEntities(int index) {
    return removedEntities_.get(index);
  }
  /**
   * <code>repeated string removedEntities = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the removedEntities at the given index.
   */
  public com.google.protobuf.ByteString
      getRemovedEntitiesBytes(int index) {
    return removedEntities_.getByteString(index);
  }

  public static final int REMOVEDTERRAIN_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList removedTerrain_;
  /**
   * <code>repeated string removedTerrain = 4;</code>
   * @return A list containing the removedTerrain.
   */
  public com.google.protobuf.ProtocolStringList
      getRemovedTerrainList() {
    return removedTerrain_;
  }
  /**
   * <code>repeated string removedTerrain = 4;</code>
   * @return The count of removedTerrain.
   */
  public int getRemovedTerrainCount() {
    return removedTerrain_.size();
  }
  /**
   * <code>repeated string removedTerrain = 4;</code>
   * @param index The index of the element to return.
   * @return The removedTerrain at the given index.
   */
  public String getRemovedTerrain(int index) {
    return removedTerrain_.get(index);
  }
  /**
   * <code>repeated string removedTerrain = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the removedTerrain at the given index.
   */
  public com.google.protobuf.ByteString
      getRemovedTerrainBytes(int index) {
    return removedTerrain_.getByteString(index);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 5;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (partialState_ != null) {
      output.writeMessage(1, getPartialState());
    }
    if (!getWorldSessionIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, worldSessionID_);
    }
    for (int i = 0; i < removedEntities_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, removedEntities_.getRaw(i));
    }
    for (int i = 0; i < removedTerrain_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, removedTerrain_.getRaw(i));
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(5, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (partialState_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPartialState());
    }
    if (!getWorldSessionIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, worldSessionID_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < removedEntities_.size(); i++) {
        dataSize += computeStringSizeNoTag(removedEntities_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRemovedEntitiesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < removedTerrain_.size(); i++) {
        dataSize += computeStringSizeNoTag(removedTerrain_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRemovedTerrainList().size();
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AMCStateUpdateProto)) {
      return super.equals(obj);
    }
    AMCStateUpdateProto other = (AMCStateUpdateProto) obj;

    if (hasPartialState() != other.hasPartialState()) return false;
    if (hasPartialState()) {
      if (!getPartialState()
          .equals(other.getPartialState())) return false;
    }
    if (!getWorldSessionID()
        .equals(other.getWorldSessionID())) return false;
    if (!getRemovedEntitiesList()
        .equals(other.getRemovedEntitiesList())) return false;
    if (!getRemovedTerrainList()
        .equals(other.getRemovedTerrainList())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPartialState()) {
      hash = (37 * hash) + PARTIALSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getPartialState().hashCode();
    }
    hash = (37 * hash) + WORLDSESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + getWorldSessionID().hashCode();
    if (getRemovedEntitiesCount() > 0) {
      hash = (37 * hash) + REMOVEDENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + getRemovedEntitiesList().hashCode();
    }
    if (getRemovedTerrainCount() > 0) {
      hash = (37 * hash) + REMOVEDTERRAIN_FIELD_NUMBER;
      hash = (53 * hash) + getRemovedTerrainList().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AMCStateUpdateProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AMCStateUpdateProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AMCStateUpdateProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AMCStateUpdateProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AMCStateUpdateProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AMCStateUpdateProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AMCStateUpdateProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AMCStateUpdateProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AMCStateUpdateProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AMCStateUpdateProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AMCStateUpdateProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AMCStateUpdateProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AMCStateUpdateProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.nkasenides.amc.proto.AMCStateUpdateProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.nkasenides.amc.proto.AMCStateUpdateProto)
      AMCStateUpdateProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AMCProto.internal_static_com_nkasenides_amc_proto_AMCStateUpdateProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AMCProto.internal_static_com_nkasenides_amc_proto_AMCStateUpdateProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AMCStateUpdateProto.class, Builder.class);
    }

    // Construct using com.nkasenides.amc.proto.AMCStateUpdateProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (partialStateBuilder_ == null) {
        partialState_ = null;
      } else {
        partialState_ = null;
        partialStateBuilder_ = null;
      }
      worldSessionID_ = "";

      removedEntities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      removedTerrain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return AMCProto.internal_static_com_nkasenides_amc_proto_AMCStateUpdateProto_descriptor;
    }

    @Override
    public AMCStateUpdateProto getDefaultInstanceForType() {
      return AMCStateUpdateProto.getDefaultInstance();
    }

    @Override
    public AMCStateUpdateProto build() {
      AMCStateUpdateProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public AMCStateUpdateProto buildPartial() {
      AMCStateUpdateProto result = new AMCStateUpdateProto(this);
      int from_bitField0_ = bitField0_;
      if (partialStateBuilder_ == null) {
        result.partialState_ = partialState_;
      } else {
        result.partialState_ = partialStateBuilder_.build();
      }
      result.worldSessionID_ = worldSessionID_;
      if (((bitField0_ & 0x00000001) != 0)) {
        removedEntities_ = removedEntities_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.removedEntities_ = removedEntities_;
      if (((bitField0_ & 0x00000002) != 0)) {
        removedTerrain_ = removedTerrain_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.removedTerrain_ = removedTerrain_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AMCStateUpdateProto) {
        return mergeFrom((AMCStateUpdateProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AMCStateUpdateProto other) {
      if (other == AMCStateUpdateProto.getDefaultInstance()) return this;
      if (other.hasPartialState()) {
        mergePartialState(other.getPartialState());
      }
      if (!other.getWorldSessionID().isEmpty()) {
        worldSessionID_ = other.worldSessionID_;
        onChanged();
      }
      if (!other.removedEntities_.isEmpty()) {
        if (removedEntities_.isEmpty()) {
          removedEntities_ = other.removedEntities_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRemovedEntitiesIsMutable();
          removedEntities_.addAll(other.removedEntities_);
        }
        onChanged();
      }
      if (!other.removedTerrain_.isEmpty()) {
        if (removedTerrain_.isEmpty()) {
          removedTerrain_ = other.removedTerrain_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureRemovedTerrainIsMutable();
          removedTerrain_.addAll(other.removedTerrain_);
        }
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AMCStateUpdateProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AMCStateUpdateProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private AMCPartialStateProto partialState_;
    private com.google.protobuf.SingleFieldBuilderV3<
        AMCPartialStateProto, AMCPartialStateProto.Builder, AMCPartialStateProtoOrBuilder> partialStateBuilder_;
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     * @return Whether the partialState field is set.
     */
    public boolean hasPartialState() {
      return partialStateBuilder_ != null || partialState_ != null;
    }
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     * @return The partialState.
     */
    public AMCPartialStateProto getPartialState() {
      if (partialStateBuilder_ == null) {
        return partialState_ == null ? AMCPartialStateProto.getDefaultInstance() : partialState_;
      } else {
        return partialStateBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     */
    public Builder setPartialState(AMCPartialStateProto value) {
      if (partialStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        partialState_ = value;
        onChanged();
      } else {
        partialStateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     */
    public Builder setPartialState(
        AMCPartialStateProto.Builder builderForValue) {
      if (partialStateBuilder_ == null) {
        partialState_ = builderForValue.build();
        onChanged();
      } else {
        partialStateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     */
    public Builder mergePartialState(AMCPartialStateProto value) {
      if (partialStateBuilder_ == null) {
        if (partialState_ != null) {
          partialState_ =
            AMCPartialStateProto.newBuilder(partialState_).mergeFrom(value).buildPartial();
        } else {
          partialState_ = value;
        }
        onChanged();
      } else {
        partialStateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     */
    public Builder clearPartialState() {
      if (partialStateBuilder_ == null) {
        partialState_ = null;
        onChanged();
      } else {
        partialState_ = null;
        partialStateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     */
    public AMCPartialStateProto.Builder getPartialStateBuilder() {
      
      onChanged();
      return getPartialStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     */
    public AMCPartialStateProtoOrBuilder getPartialStateOrBuilder() {
      if (partialStateBuilder_ != null) {
        return partialStateBuilder_.getMessageOrBuilder();
      } else {
        return partialState_ == null ?
            AMCPartialStateProto.getDefaultInstance() : partialState_;
      }
    }
    /**
     * <code>.com.nkasenides.amc.proto.AMCPartialStateProto partialState = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        AMCPartialStateProto, AMCPartialStateProto.Builder, AMCPartialStateProtoOrBuilder>
        getPartialStateFieldBuilder() {
      if (partialStateBuilder_ == null) {
        partialStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            AMCPartialStateProto, AMCPartialStateProto.Builder, AMCPartialStateProtoOrBuilder>(
                getPartialState(),
                getParentForChildren(),
                isClean());
        partialState_ = null;
      }
      return partialStateBuilder_;
    }

    private Object worldSessionID_ = "";
    /**
     * <code>string worldSessionID = 2;</code>
     * @return The worldSessionID.
     */
    public String getWorldSessionID() {
      Object ref = worldSessionID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        worldSessionID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string worldSessionID = 2;</code>
     * @return The bytes for worldSessionID.
     */
    public com.google.protobuf.ByteString
        getWorldSessionIDBytes() {
      Object ref = worldSessionID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        worldSessionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string worldSessionID = 2;</code>
     * @param value The worldSessionID to set.
     * @return This builder for chaining.
     */
    public Builder setWorldSessionID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      worldSessionID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string worldSessionID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorldSessionID() {
      
      worldSessionID_ = getDefaultInstance().getWorldSessionID();
      onChanged();
      return this;
    }
    /**
     * <code>string worldSessionID = 2;</code>
     * @param value The bytes for worldSessionID to set.
     * @return This builder for chaining.
     */
    public Builder setWorldSessionIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      worldSessionID_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList removedEntities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRemovedEntitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        removedEntities_ = new com.google.protobuf.LazyStringArrayList(removedEntities_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @return A list containing the removedEntities.
     */
    public com.google.protobuf.ProtocolStringList
        getRemovedEntitiesList() {
      return removedEntities_.getUnmodifiableView();
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @return The count of removedEntities.
     */
    public int getRemovedEntitiesCount() {
      return removedEntities_.size();
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @param index The index of the element to return.
     * @return The removedEntities at the given index.
     */
    public String getRemovedEntities(int index) {
      return removedEntities_.get(index);
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the removedEntities at the given index.
     */
    public com.google.protobuf.ByteString
        getRemovedEntitiesBytes(int index) {
      return removedEntities_.getByteString(index);
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @param index The index to set the value at.
     * @param value The removedEntities to set.
     * @return This builder for chaining.
     */
    public Builder setRemovedEntities(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRemovedEntitiesIsMutable();
      removedEntities_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @param value The removedEntities to add.
     * @return This builder for chaining.
     */
    public Builder addRemovedEntities(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRemovedEntitiesIsMutable();
      removedEntities_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @param values The removedEntities to add.
     * @return This builder for chaining.
     */
    public Builder addAllRemovedEntities(
        Iterable<String> values) {
      ensureRemovedEntitiesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, removedEntities_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemovedEntities() {
      removedEntities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string removedEntities = 3;</code>
     * @param value The bytes of the removedEntities to add.
     * @return This builder for chaining.
     */
    public Builder addRemovedEntitiesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRemovedEntitiesIsMutable();
      removedEntities_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList removedTerrain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRemovedTerrainIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        removedTerrain_ = new com.google.protobuf.LazyStringArrayList(removedTerrain_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @return A list containing the removedTerrain.
     */
    public com.google.protobuf.ProtocolStringList
        getRemovedTerrainList() {
      return removedTerrain_.getUnmodifiableView();
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @return The count of removedTerrain.
     */
    public int getRemovedTerrainCount() {
      return removedTerrain_.size();
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @param index The index of the element to return.
     * @return The removedTerrain at the given index.
     */
    public String getRemovedTerrain(int index) {
      return removedTerrain_.get(index);
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the removedTerrain at the given index.
     */
    public com.google.protobuf.ByteString
        getRemovedTerrainBytes(int index) {
      return removedTerrain_.getByteString(index);
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @param index The index to set the value at.
     * @param value The removedTerrain to set.
     * @return This builder for chaining.
     */
    public Builder setRemovedTerrain(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRemovedTerrainIsMutable();
      removedTerrain_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @param value The removedTerrain to add.
     * @return This builder for chaining.
     */
    public Builder addRemovedTerrain(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRemovedTerrainIsMutable();
      removedTerrain_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @param values The removedTerrain to add.
     * @return This builder for chaining.
     */
    public Builder addAllRemovedTerrain(
        Iterable<String> values) {
      ensureRemovedTerrainIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, removedTerrain_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemovedTerrain() {
      removedTerrain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string removedTerrain = 4;</code>
     * @param value The bytes of the removedTerrain to add.
     * @return This builder for chaining.
     */
    public Builder addRemovedTerrainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRemovedTerrainIsMutable();
      removedTerrain_.add(value);
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 5;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.nkasenides.amc.proto.AMCStateUpdateProto)
  }

  // @@protoc_insertion_point(class_scope:com.nkasenides.amc.proto.AMCStateUpdateProto)
  private static final AMCStateUpdateProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AMCStateUpdateProto();
  }

  public static AMCStateUpdateProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AMCStateUpdateProto>
      PARSER = new com.google.protobuf.AbstractParser<AMCStateUpdateProto>() {
    @Override
    public AMCStateUpdateProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AMCStateUpdateProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AMCStateUpdateProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AMCStateUpdateProto> getParserForType() {
    return PARSER;
  }

  @Override
  public AMCStateUpdateProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

