// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/AMCProto.proto

package com.nkasenides.amc.proto;

/**
 * Protobuf type {@code com.nkasenides.amc.proto.QuestionnaireEntryProto}
 */
public final class QuestionnaireEntryProto extends
    com.google.protobuf.GeneratedMessageV3 implements com.nkasenides.athlos.proto.Modelable<com.nkasenides.amc.model.QuestionnaireEntry> , 
    // @@protoc_insertion_point(message_implements:com.nkasenides.amc.proto.QuestionnaireEntryProto)
    QuestionnaireEntryProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuestionnaireEntryProto.newBuilder() to construct.
  private QuestionnaireEntryProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuestionnaireEntryProto() {
    challengeID_ = "";
    questionEntry_ = java.util.Collections.emptyList();
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QuestionnaireEntryProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QuestionnaireEntryProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            challengeID_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              questionEntry_ = new java.util.ArrayList<com.nkasenides.amc.proto.QuestionEntryProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            questionEntry_.add(
                input.readMessage(com.nkasenides.amc.proto.QuestionEntryProto.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        questionEntry_ = java.util.Collections.unmodifiableList(questionEntry_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nkasenides.amc.proto.AMCProto.internal_static_com_nkasenides_amc_proto_QuestionnaireEntryProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nkasenides.amc.proto.AMCProto.internal_static_com_nkasenides_amc_proto_QuestionnaireEntryProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nkasenides.amc.proto.QuestionnaireEntryProto.class, com.nkasenides.amc.proto.QuestionnaireEntryProto.Builder.class);
  }

  public static final int CHALLENGEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object challengeID_;
  /**
   * <code>string challengeID = 1;</code>
   * @return The challengeID.
   */
  @java.lang.Override
  public java.lang.String getChallengeID() {
    java.lang.Object ref = challengeID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      challengeID_ = s;
      return s;
    }
  }
  /**
   * <code>string challengeID = 1;</code>
   * @return The bytes for challengeID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChallengeIDBytes() {
    java.lang.Object ref = challengeID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      challengeID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUESTIONENTRY_FIELD_NUMBER = 2;
  private java.util.List<com.nkasenides.amc.proto.QuestionEntryProto> questionEntry_;
  /**
   * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.nkasenides.amc.proto.QuestionEntryProto> getQuestionEntryList() {
    return questionEntry_;
  }
  /**
   * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.nkasenides.amc.proto.QuestionEntryProtoOrBuilder> 
      getQuestionEntryOrBuilderList() {
    return questionEntry_;
  }
  /**
   * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
   */
  @java.lang.Override
  public int getQuestionEntryCount() {
    return questionEntry_.size();
  }
  /**
   * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
   */
  @java.lang.Override
  public com.nkasenides.amc.proto.QuestionEntryProto getQuestionEntry(int index) {
    return questionEntry_.get(index);
  }
  /**
   * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
   */
  @java.lang.Override
  public com.nkasenides.amc.proto.QuestionEntryProtoOrBuilder getQuestionEntryOrBuilder(
      int index) {
    return questionEntry_.get(index);
  }

  public static final int ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getChallengeIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, challengeID_);
    }
    for (int i = 0; i < questionEntry_.size(); i++) {
      output.writeMessage(2, questionEntry_.get(i));
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getChallengeIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, challengeID_);
    }
    for (int i = 0; i < questionEntry_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, questionEntry_.get(i));
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nkasenides.amc.proto.QuestionnaireEntryProto)) {
      return super.equals(obj);
    }
    com.nkasenides.amc.proto.QuestionnaireEntryProto other = (com.nkasenides.amc.proto.QuestionnaireEntryProto) obj;

    if (!getChallengeID()
        .equals(other.getChallengeID())) return false;
    if (!getQuestionEntryList()
        .equals(other.getQuestionEntryList())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHALLENGEID_FIELD_NUMBER;
    hash = (53 * hash) + getChallengeID().hashCode();
    if (getQuestionEntryCount() > 0) {
      hash = (37 * hash) + QUESTIONENTRY_FIELD_NUMBER;
      hash = (53 * hash) + getQuestionEntryList().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nkasenides.amc.proto.QuestionnaireEntryProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nkasenides.amc.proto.QuestionnaireEntryProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.nkasenides.amc.proto.QuestionnaireEntryProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.nkasenides.amc.proto.QuestionnaireEntryProto)
      com.nkasenides.amc.proto.QuestionnaireEntryProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nkasenides.amc.proto.AMCProto.internal_static_com_nkasenides_amc_proto_QuestionnaireEntryProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nkasenides.amc.proto.AMCProto.internal_static_com_nkasenides_amc_proto_QuestionnaireEntryProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nkasenides.amc.proto.QuestionnaireEntryProto.class, com.nkasenides.amc.proto.QuestionnaireEntryProto.Builder.class);
    }

    // Construct using com.nkasenides.amc.proto.QuestionnaireEntryProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getQuestionEntryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      challengeID_ = "";

      if (questionEntryBuilder_ == null) {
        questionEntry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        questionEntryBuilder_.clear();
      }
      id_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nkasenides.amc.proto.AMCProto.internal_static_com_nkasenides_amc_proto_QuestionnaireEntryProto_descriptor;
    }

    @java.lang.Override
    public com.nkasenides.amc.proto.QuestionnaireEntryProto getDefaultInstanceForType() {
      return com.nkasenides.amc.proto.QuestionnaireEntryProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.nkasenides.amc.proto.QuestionnaireEntryProto build() {
      com.nkasenides.amc.proto.QuestionnaireEntryProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nkasenides.amc.proto.QuestionnaireEntryProto buildPartial() {
      com.nkasenides.amc.proto.QuestionnaireEntryProto result = new com.nkasenides.amc.proto.QuestionnaireEntryProto(this);
      int from_bitField0_ = bitField0_;
      result.challengeID_ = challengeID_;
      if (questionEntryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          questionEntry_ = java.util.Collections.unmodifiableList(questionEntry_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.questionEntry_ = questionEntry_;
      } else {
        result.questionEntry_ = questionEntryBuilder_.build();
      }
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nkasenides.amc.proto.QuestionnaireEntryProto) {
        return mergeFrom((com.nkasenides.amc.proto.QuestionnaireEntryProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nkasenides.amc.proto.QuestionnaireEntryProto other) {
      if (other == com.nkasenides.amc.proto.QuestionnaireEntryProto.getDefaultInstance()) return this;
      if (!other.getChallengeID().isEmpty()) {
        challengeID_ = other.challengeID_;
        onChanged();
      }
      if (questionEntryBuilder_ == null) {
        if (!other.questionEntry_.isEmpty()) {
          if (questionEntry_.isEmpty()) {
            questionEntry_ = other.questionEntry_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureQuestionEntryIsMutable();
            questionEntry_.addAll(other.questionEntry_);
          }
          onChanged();
        }
      } else {
        if (!other.questionEntry_.isEmpty()) {
          if (questionEntryBuilder_.isEmpty()) {
            questionEntryBuilder_.dispose();
            questionEntryBuilder_ = null;
            questionEntry_ = other.questionEntry_;
            bitField0_ = (bitField0_ & ~0x00000001);
            questionEntryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getQuestionEntryFieldBuilder() : null;
          } else {
            questionEntryBuilder_.addAllMessages(other.questionEntry_);
          }
        }
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nkasenides.amc.proto.QuestionnaireEntryProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nkasenides.amc.proto.QuestionnaireEntryProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object challengeID_ = "";
    /**
     * <code>string challengeID = 1;</code>
     * @return The challengeID.
     */
    public java.lang.String getChallengeID() {
      java.lang.Object ref = challengeID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        challengeID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string challengeID = 1;</code>
     * @return The bytes for challengeID.
     */
    public com.google.protobuf.ByteString
        getChallengeIDBytes() {
      java.lang.Object ref = challengeID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        challengeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string challengeID = 1;</code>
     * @param value The challengeID to set.
     * @return This builder for chaining.
     */
    public Builder setChallengeID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      challengeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string challengeID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChallengeID() {
      
      challengeID_ = getDefaultInstance().getChallengeID();
      onChanged();
      return this;
    }
    /**
     * <code>string challengeID = 1;</code>
     * @param value The bytes for challengeID to set.
     * @return This builder for chaining.
     */
    public Builder setChallengeIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      challengeID_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.nkasenides.amc.proto.QuestionEntryProto> questionEntry_ =
      java.util.Collections.emptyList();
    private void ensureQuestionEntryIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        questionEntry_ = new java.util.ArrayList<com.nkasenides.amc.proto.QuestionEntryProto>(questionEntry_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nkasenides.amc.proto.QuestionEntryProto, com.nkasenides.amc.proto.QuestionEntryProto.Builder, com.nkasenides.amc.proto.QuestionEntryProtoOrBuilder> questionEntryBuilder_;

    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public java.util.List<com.nkasenides.amc.proto.QuestionEntryProto> getQuestionEntryList() {
      if (questionEntryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(questionEntry_);
      } else {
        return questionEntryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public int getQuestionEntryCount() {
      if (questionEntryBuilder_ == null) {
        return questionEntry_.size();
      } else {
        return questionEntryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public com.nkasenides.amc.proto.QuestionEntryProto getQuestionEntry(int index) {
      if (questionEntryBuilder_ == null) {
        return questionEntry_.get(index);
      } else {
        return questionEntryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder setQuestionEntry(
        int index, com.nkasenides.amc.proto.QuestionEntryProto value) {
      if (questionEntryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionEntryIsMutable();
        questionEntry_.set(index, value);
        onChanged();
      } else {
        questionEntryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder setQuestionEntry(
        int index, com.nkasenides.amc.proto.QuestionEntryProto.Builder builderForValue) {
      if (questionEntryBuilder_ == null) {
        ensureQuestionEntryIsMutable();
        questionEntry_.set(index, builderForValue.build());
        onChanged();
      } else {
        questionEntryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder addQuestionEntry(com.nkasenides.amc.proto.QuestionEntryProto value) {
      if (questionEntryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionEntryIsMutable();
        questionEntry_.add(value);
        onChanged();
      } else {
        questionEntryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder addQuestionEntry(
        int index, com.nkasenides.amc.proto.QuestionEntryProto value) {
      if (questionEntryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestionEntryIsMutable();
        questionEntry_.add(index, value);
        onChanged();
      } else {
        questionEntryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder addQuestionEntry(
        com.nkasenides.amc.proto.QuestionEntryProto.Builder builderForValue) {
      if (questionEntryBuilder_ == null) {
        ensureQuestionEntryIsMutable();
        questionEntry_.add(builderForValue.build());
        onChanged();
      } else {
        questionEntryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder addQuestionEntry(
        int index, com.nkasenides.amc.proto.QuestionEntryProto.Builder builderForValue) {
      if (questionEntryBuilder_ == null) {
        ensureQuestionEntryIsMutable();
        questionEntry_.add(index, builderForValue.build());
        onChanged();
      } else {
        questionEntryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder addAllQuestionEntry(
        java.lang.Iterable<? extends com.nkasenides.amc.proto.QuestionEntryProto> values) {
      if (questionEntryBuilder_ == null) {
        ensureQuestionEntryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, questionEntry_);
        onChanged();
      } else {
        questionEntryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder clearQuestionEntry() {
      if (questionEntryBuilder_ == null) {
        questionEntry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        questionEntryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public Builder removeQuestionEntry(int index) {
      if (questionEntryBuilder_ == null) {
        ensureQuestionEntryIsMutable();
        questionEntry_.remove(index);
        onChanged();
      } else {
        questionEntryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public com.nkasenides.amc.proto.QuestionEntryProto.Builder getQuestionEntryBuilder(
        int index) {
      return getQuestionEntryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public com.nkasenides.amc.proto.QuestionEntryProtoOrBuilder getQuestionEntryOrBuilder(
        int index) {
      if (questionEntryBuilder_ == null) {
        return questionEntry_.get(index);  } else {
        return questionEntryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public java.util.List<? extends com.nkasenides.amc.proto.QuestionEntryProtoOrBuilder> 
         getQuestionEntryOrBuilderList() {
      if (questionEntryBuilder_ != null) {
        return questionEntryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(questionEntry_);
      }
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public com.nkasenides.amc.proto.QuestionEntryProto.Builder addQuestionEntryBuilder() {
      return getQuestionEntryFieldBuilder().addBuilder(
          com.nkasenides.amc.proto.QuestionEntryProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public com.nkasenides.amc.proto.QuestionEntryProto.Builder addQuestionEntryBuilder(
        int index) {
      return getQuestionEntryFieldBuilder().addBuilder(
          index, com.nkasenides.amc.proto.QuestionEntryProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.nkasenides.amc.proto.QuestionEntryProto questionEntry = 2;</code>
     */
    public java.util.List<com.nkasenides.amc.proto.QuestionEntryProto.Builder> 
         getQuestionEntryBuilderList() {
      return getQuestionEntryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nkasenides.amc.proto.QuestionEntryProto, com.nkasenides.amc.proto.QuestionEntryProto.Builder, com.nkasenides.amc.proto.QuestionEntryProtoOrBuilder> 
        getQuestionEntryFieldBuilder() {
      if (questionEntryBuilder_ == null) {
        questionEntryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.nkasenides.amc.proto.QuestionEntryProto, com.nkasenides.amc.proto.QuestionEntryProto.Builder, com.nkasenides.amc.proto.QuestionEntryProtoOrBuilder>(
                questionEntry_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        questionEntry_ = null;
      }
      return questionEntryBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 3;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 3;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.nkasenides.amc.proto.QuestionnaireEntryProto)
  }

  // @@protoc_insertion_point(class_scope:com.nkasenides.amc.proto.QuestionnaireEntryProto)
  private static final com.nkasenides.amc.proto.QuestionnaireEntryProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nkasenides.amc.proto.QuestionnaireEntryProto();
  }

  public static com.nkasenides.amc.proto.QuestionnaireEntryProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuestionnaireEntryProto>
      PARSER = new com.google.protobuf.AbstractParser<QuestionnaireEntryProto>() {
    @java.lang.Override
    public QuestionnaireEntryProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QuestionnaireEntryProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuestionnaireEntryProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QuestionnaireEntryProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nkasenides.amc.proto.QuestionnaireEntryProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

    @java.lang.Override    
    public com.nkasenides.amc.model.QuestionnaireEntry toObject() {    
        com.nkasenides.amc.model.QuestionnaireEntry item = new com.nkasenides.amc.model.QuestionnaireEntry();        
        item.setChallengeID(getChallengeID());        
        java.util.ArrayList<com.nkasenides.amc.model.QuestionEntry> questionEntryList = new java.util.ArrayList<>();        
        for (int i = 0; i < getQuestionEntryCount(); i++) {        
            questionEntryList.add(getQuestionEntry(i).toObject());            
        }        
        item.setQuestionEntry(questionEntryList);        
        item.setId(getId());        
        return item;        
    }    
    
        public java.util.List<QuestionEntryProto> getQuestionEntry() {
        return questionEntry_;
    }
    
}

