// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/AMCProto.proto

package com.nkasenides.amc.proto;

public interface UnsubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.amc.proto.UnsubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string worldSessionID = 1;</code>
   * @return The worldSessionID.
   */
  String getWorldSessionID();
  /**
   * <code>string worldSessionID = 1;</code>
   * @return The bytes for worldSessionID.
   */
  com.google.protobuf.ByteString
      getWorldSessionIDBytes();
}
