const colors = {
    0: "gold",
    1: "blue",
    2: "purple",
    3: "green",
    4: "darkblue",
    5: "indigo",
    6: "red",
    7: "lightgray",
    8: "pink",
    9: "lime",
    10:"darkred",
    11: "darkgray",
    12: "black",
    13: "magenta",
    14: "yellow",
    15: "darkgreen",
    16: "teal",
    17: "cyan",
    18: "gray",
    19: "orange"
}

const colorNames = {
    0: "Gold",
    1: "Blue",
    2: "Purple",
    3: "Green",
    4: "Dark blue",
    5: "Indigo",
    6: "Red",
    7: "Light gray",
    8: "Pink",
    9: "Lime",
    10:"Dark red",
    11: "Dark gray",
    12: "Black",
    13: "Magenta",
    14: "Yellow",
    15: "Dark green",
    16: "Teal",
    17: "Cyan",
    18: "Gray",
    19: "Orange"
}