/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 12-08-2021 11:56:05
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package com.nkasenides.amc.auth;
import com.nkasenides.amc.persistence.*;
import com.nkasenides.amc.model.AMCPlayer;

public final class Auth {

    public static AMCPlayer verifyGameSessionID(final String gameSessionID) {
        return DBManager.gameSession.getPlayer(gameSessionID);
    }

    public static AMCPlayer verifyWorldSessionID(final String worldSessionID) {
        return DBManager.worldSession.getPlayer(worldSessionID);
    }

}

