/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 17-08-2021 12:37:25
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package org.inspirecenter.amazechallenge.servlet.admin;

import com.raylabz.firestorm.Firestorm;
import org.inspirecenter.amazechallenge.model.*;
import org.inspirecenter.amazechallenge.persistence.DBManager;
import org.inspirecenter.amazechallenge.proto.*;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.HashMap;
import java.util.UUID;
import java.util.stream.Collectors;

public class AuthenticateAdminServlet extends HttpServlet {
    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        final String adminKey = req.getParameter("adminKey");

        final AdminKey adminKeyServer = DBManager.adminKey.get();

        if (adminKeyServer == null) {
            resp.getWriter().write("Error: No admin key on server");
            return;
        }

        if (!adminKeyServer.getId().equals(adminKey)) {
            resp.getWriter().write("Error: Invalid admin key");
            return;
        }

        resp.getWriter().write("OK");

    }
}