// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/AMCProto.proto

package org.inspirecenter.amazechallenge.proto;

/**
 * Protobuf enum {@code BackgroundImageType}
 */
public enum BackgroundImageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>JPG_BackgroundImageType = 0;</code>
   */
  JPG_BackgroundImageType(0),
  /**
   * <code>GIF_BackgroundImageType = 1;</code>
   */
  GIF_BackgroundImageType(1),
  /**
   * <code>PNG_BackgroundImageType = 2;</code>
   */
  PNG_BackgroundImageType(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>JPG_BackgroundImageType = 0;</code>
   */
  public static final int JPG_BackgroundImageType_VALUE = 0;
  /**
   * <code>GIF_BackgroundImageType = 1;</code>
   */
  public static final int GIF_BackgroundImageType_VALUE = 1;
  /**
   * <code>PNG_BackgroundImageType = 2;</code>
   */
  public static final int PNG_BackgroundImageType_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static BackgroundImageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static BackgroundImageType forNumber(int value) {
    switch (value) {
      case 0: return JPG_BackgroundImageType;
      case 1: return GIF_BackgroundImageType;
      case 2: return PNG_BackgroundImageType;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BackgroundImageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BackgroundImageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BackgroundImageType>() {
          public BackgroundImageType findValueByNumber(int number) {
            return BackgroundImageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return AMCProto.getDescriptor().getEnumTypes().get(14);
  }

  private static final BackgroundImageType[] VALUES = values();

  public static BackgroundImageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BackgroundImageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:BackgroundImageType)
}

