// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/AMCProto.proto

package org.inspirecenter.amazechallenge.proto;

public interface PlayerEntityProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerEntityProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string worldID = 8;</code>
   * @return The worldID.
   */
  String getWorldID();
  /**
   * <code>string worldID = 8;</code>
   * @return The bytes for worldID.
   */
  com.google.protobuf.ByteString
      getWorldIDBytes();

  /**
   * <code>float areaOfInterest = 9;</code>
   * @return The areaOfInterest.
   */
  float getAreaOfInterest();

  /**
   * <code>string id = 10;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 10;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.MatrixPositionProto position = 11;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.MatrixPositionProto position = 11;</code>
   * @return The position.
   */
  MatrixPositionProto getPosition();
  /**
   * <code>.MatrixPositionProto position = 11;</code>
   */
  MatrixPositionProtoOrBuilder getPositionOrBuilder();

  /**
   * <code>string playerID = 12;</code>
   * @return The playerID.
   */
  String getPlayerID();
  /**
   * <code>string playerID = 12;</code>
   * @return The bytes for playerID.
   */
  com.google.protobuf.ByteString
      getPlayerIDBytes();

  /**
   * <code>.Direction4 direction = 13;</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>.Direction4 direction = 13;</code>
   * @return The direction.
   */
  Direction4 getDirection();
}
