// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/AMCProto.proto

package org.inspirecenter.amazechallenge.proto;

public interface QuestionEntryProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.amc.proto.QuestionEntryProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string answerText = 1;</code>
   * @return The answerText.
   */
  String getAnswerText();
  /**
   * <code>string answerText = 1;</code>
   * @return The bytes for answerText.
   */
  com.google.protobuf.ByteString
      getAnswerTextBytes();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string questionText = 3;</code>
   * @return The questionText.
   */
  String getQuestionText();
  /**
   * <code>string questionText = 3;</code>
   * @return The bytes for questionText.
   */
  com.google.protobuf.ByteString
      getQuestionTextBytes();
}
