/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 17-08-2021 12:52:55
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package com.nkasenides.amc.model;

import com.nkasenides.athlos.proto.Transmittable;
import com.nkasenides.amc.proto.*;
import com.nkasenides.athlos.model.*;
import com.raylabz.firestorm.annotation.FirestormObject;

@FirestormObject
public class AdminKey implements Transmittable<AdminKeyProto.Builder> {
    private String id;    

    public String getId() {    
        return id;        
    }    
    

    public void setId(String id) {    
        this.id = id;        
    }    
    

    @Override    
    public com.nkasenides.amc.proto.AdminKeyProto.Builder toProto() {    
        com.nkasenides.amc.proto.AdminKeyProto.Builder protoBuilder = com.nkasenides.amc.proto.AdminKeyProto.newBuilder();        
        protoBuilder.setId(id);        
        return protoBuilder;        
    }    
    

}
