/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 17-08-2021 12:37:25
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package com.nkasenides.amc.service;
import com.nkasenides.athlos.backend.AthlosService;
import com.nkasenides.amc.proto.JoinChallengeRequest;
import com.nkasenides.amc.auth.*;
import com.nkasenides.amc.proto.JoinChallengeResponse;

public class JoinChallenge implements AthlosService<JoinChallengeRequest, JoinChallengeResponse> {

    @Override    
    public JoinChallengeResponse serve(JoinChallengeRequest request, Object... additionalParams) {    
        //TODO - Implement this service.        
        return null;        
    }    
    
}

