/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 17-08-2021 12:37:25
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package com.nkasenides.amc.service;
import com.nkasenides.athlos.backend.AthlosService;
import com.nkasenides.amc.proto.ListChallengesRequest;
import com.nkasenides.amc.auth.*;
import com.nkasenides.amc.proto.ListChallengesResponse;

public class ListChallenges implements AthlosService<ListChallengesRequest, ListChallengesResponse> {

    @Override    
    public ListChallengesResponse serve(ListChallengesRequest request, Object... additionalParams) {    
        //TODO - Implement this service.        
        return null;        
    }    
    
}

