/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 12-08-2021 11:56:05
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package org.inspirecenter.amazechallenge.persistence;


import com.nkasenides.athlos.persistence.*;
import org.inspirecenter.amazechallenge.model.*;
import com.raylabz.firestorm.Firestorm;
import com.raylabz.firestorm.QueryResult;
import org.inspirecenter.amazechallenge.model.AMCPlayer;
import org.inspirecenter.amazechallenge.model.AMCWorldSession;

import java.util.List;
import java.util.Collection;


public class AMCWorldSessionDAO implements WorldBasedDAO<AMCWorldSession> {


    @Override
    public boolean create(AMCWorldSession object) {
        return Firestorm.create(object) != null;
    }

    @Override
    public boolean update(AMCWorldSession object) {
        Firestorm.update(object);
        return true;
    }

    @Override
    public boolean delete(AMCWorldSession object) {
        Firestorm.delete(object);
        return true;
    }

    @Override
    public AMCWorldSession get(String id) {
        return Firestorm.get(AMCWorldSession.class, id);
    }

    @Override
    public AMCWorldSession getForWorld(String worldID, String itemID) {
        final QueryResult<AMCWorldSession> result = Firestorm.filter(AMCWorldSession.class)
                .whereEqualTo("worldID", worldID)
                .whereEqualTo("id", itemID)
                .limit(1)
                .fetch();
        if (result.hasItems()) {
            return result.getItems().get(0);
        }
        return null;
    }

    @Override
    public Collection<AMCWorldSession> listForWorld(String worldID) {
        return Firestorm.filter(AMCWorldSession.class)
                .whereEqualTo("worldID", worldID)
                .fetch().getItems();
    }

    /**
     * Retrieves the player of the provided session.
     * @param worldSessionID The session's ID.
     * @return Returns a player object 
     */
    public AMCPlayer getPlayer(final String worldSessionID) {
        final AMCWorldSession amcWorldSession = Firestorm.get(AMCWorldSession.class, worldSessionID);
        return Firestorm.get(AMCPlayer.class, amcWorldSession.getPlayerID());
    }

    /**
     * Retrieves the world sessions owned by the provided player.
     * @param playerID The player's ID.
     * @return Returns a WorldSession, or null.
     */
    public Collection<AMCWorldSession> listForPlayer(final String playerID) {
        return Firestorm.filter(AMCWorldSession.class)
                .whereEqualTo("playerID", playerID)
                .fetch().getItems();
    }

    /**
     * Retrieves the world session for the specific player in a specific world.
     * @param playerID The player ID.
     * @param worldID The world ID.
     * @return Returns a WorldSession.
     */

    public AMCWorldSession getForPlayerAndWorld(final String playerID, final String worldID) {
        final QueryResult<AMCWorldSession> result = Firestorm.filter(AMCWorldSession.class)
                .whereEqualTo("playerID", playerID)
                .whereEqualTo("worldID", worldID)
                .limit(1)
                .fetch();
        if (result.hasItems()) {
            return result.getItems().get(0);
        }
        return null;
    }

    /**
     * Retrieves multiple world sessions using the provided IDs.
     * @param ids A list of world session IDs.
     * @return Returns a list of world sessions.
     */
    public List<AMCWorldSession> getMany(List<String> ids) {
        return Firestorm.getMany(AMCWorldSession.class, ids);
    }


}


