///* --------------------------------------------------------------------------------
//  This file was automatically generated by the Athlos Project Editor.
//  Athlos Framework: http://nkasenides.github.io/athlos
//  Generated on: 12-08-2021 11:56:05
//  Athlos Project Editor, v0.1.0 BETA
//-------------------------------------------------------------------------------- */
//
//package com.nkasenides.amc.persistence;
//
//
//import com.nkasenides.athlos.persistence.*;
//import com.nkasenides.amc.model.*;
//import java.util.List;
//import java.util.Collection;
//
//
//public class AMCTeamDAO implements MultiDAO<AMCTeam> {
//
//
//    @Override
//    public boolean create(AMCTeam object) {
//        //TODO - Implement
//        return false;
//    }
//
//    @Override
//    public boolean update(AMCTeam object) {
//        //TODO - Implement
//        return false;
//    }
//
//    @Override
//    public boolean delete(AMCTeam object) {
//        //TODO - Implement
//        return false;
//    }
//
//    @Override
//    public AMCTeam get(String id) {
//        //TODO - Implement
//        return null;
//    }
//
//    @Override
//    public Collection<AMCTeam> getMany(String... ids) {
//        //TODO - Implement
//        return null;
//    }
//
//    @Override
//    public Collection<AMCTeam> list() {
//        //TODO - Implement
//        return null;
//    }
//
//    @Override
//    public boolean create(Collection<AMCTeam> objects) {
//        //TODO - Implement
//        return false;
//    }
//
//    @Override
//    public boolean update(Collection<AMCTeam> objects) {
//        //TODO - Implement
//        return false;
//    }
//
//    @Override
//    public boolean delete(Collection<AMCTeam> objects) {
//        //TODO - Implement
//        return false;
//    }
//
//
///**
//     * Lists all of the players of a particular team.
//     * @param teamID The team's ID.
//     * @return Returns a collection of Players.
//     */
//    public Collection<AMCPlayer> listPlayers(String teamID) {
//        //TODO - Implement
//        return null;
//    }
//
//}
//
//
