/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 12-08-2021 11:56:05
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package com.nkasenides.amc.persistence;


import com.nkasenides.athlos.persistence.*;
import com.nkasenides.amc.model.*;
import java.util.List;
import java.util.Collection;


public class AMCWorldSessionDAO implements WorldBasedDAO<AMCWorldSession> {


    @Override
    public boolean create(AMCWorldSession object) {
        //TODO - Implement
        return false;
    }

    @Override
    public boolean update(AMCWorldSession object) {
        //TODO - Implement
        return false;
    }

    @Override
    public boolean delete(AMCWorldSession object) {
        //TODO - Implement
        return false;
    }

    @Override
    public AMCWorldSession get(String itemID) {
        //TODO - Implement
        return null;
    }

    @Override
    public AMCWorldSession getForWorld(String worldID, String itemID) {
        //TODO - Implement
        return null;
    }

    @Override
    public Collection<AMCWorldSession> listForWorld(String worldID) {
        //TODO - Implement
        return null;
    }

    /**
     * Retrieves the player of the provided session.
     * @param worldSessionID The session's ID.
     * @return Returns a player object 
     */
    public AMCPlayer getPlayer(final String worldSessionID) {
        //TODO Implement
        return null;
    }

    /**
     * Retrieves the world sessions owned by the provided player.
     * @param playerID The player's ID.
     * @return Returns a WorldSession, or null.
     */
    public Collection<AMCWorldSession> listForPlayer(final String playerID) {
        //TODO - Implement
        return null;
    }

    /**
     * Retrieves the world session for the specific player in a specific world.
     * @param playerID The player ID.
     * @param worldID The world ID.
     * @return Returns a WorldSession.
     */

    public AMCWorldSession getForPlayerAndWorld(final String playerID, final String worldID) {
        //TODO - Implement
        return null;
    }

    /**
     * Retrieves multiple world sessions using the provided IDs.
     * @param ids A list of world session IDs.
     * @return Returns a list of world sessions.
     */
    public List<AMCWorldSession> getMany(List<String> ids) {
        //TODO - Implement
        return null;
    }


}


