/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 12-08-2021 11:56:05
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package com.nkasenides.amc.persistence;


import com.nkasenides.athlos.persistence.*;
import com.nkasenides.amc.model.*;
import com.raylabz.firestorm.Firestorm;
import com.raylabz.firestorm.FirestormBatch;

import java.util.List;
import java.util.Collection;


public class QuestionEntryDAO implements MultiDAO<QuestionEntry> {


    @Override
    public boolean create(QuestionEntry object) {
        return Firestorm.create(object) != null;
    }

    @Override
    public boolean update(QuestionEntry object) {
        Firestorm.update(object);
        return true;
    }

    @Override
    public boolean delete(QuestionEntry object) {
        Firestorm.delete(object);
        return true;
    }

    @Override
    public QuestionEntry get(String id) {
        return Firestorm.get(QuestionEntry.class, id);
    }

    @Override
    public Collection<QuestionEntry> getMany(String... ids) {
        return Firestorm.getMany(QuestionEntry.class, ids);
    }

    @Override
    public Collection<QuestionEntry> list() {
        return Firestorm.listAll(QuestionEntry.class);
    }

    @Override
    public boolean create(Collection<QuestionEntry> objects) {
        Firestorm.runBatch(new FirestormBatch() {
            @Override
            public void execute() {
                for (QuestionEntry object : objects) {
                    create(object);
                }
            }

            @Override
            public void onFailure(Exception e) {

            }

            @Override
            public void onSuccess() {

            }
        });
        return true;
    }

    @Override
    public boolean update(Collection<QuestionEntry> objects) {
        Firestorm.runBatch(new FirestormBatch() {
            @Override
            public void execute() {
                for (QuestionEntry object : objects) {
                    update(object);
                }
            }

            @Override
            public void onFailure(Exception e) {

            }

            @Override
            public void onSuccess() {

            }
        });
        return true;
    }

    @Override
    public boolean delete(Collection<QuestionEntry> objects) {
        Firestorm.runBatch(new FirestormBatch() {
            @Override
            public void execute() {
                for (QuestionEntry object : objects) {
                    delete(object);
                }
            }

            @Override
            public void onFailure(Exception e) {

            }

            @Override
            public void onSuccess() {

            }
        });
        return true;
    }


}


